-- 初始化数据库脚本
-- 适用于 MySQL

-- 创建并使用数据库
CREATE DATABASE IF NOT EXISTS smartdoctor CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE smartdoctor;

-- 1. 用户信息表
CREATE TABLE IF NOT EXISTS account (
    id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'id（账号表）',
    realname VARCHAR(255) DEFAULT NULL COMMENT '姓名',
    uname VARCHAR(255) DEFAULT NULL COMMENT '用户名',
    pwd VARCHAR(255) DEFAULT NULL COMMENT '密码',
    phonenumber VARCHAR(255) DEFAULT NULL COMMENT '电话号码',
    utype VARCHAR(11) DEFAULT NULL COMMENT '角色类型：1管理员，2医生，3患者',
    updatetime DATETIME(6) DEFAULT NULL COMMENT '更新时间',
    createtime DATETIME(6) DEFAULT NULL COMMENT '创建时间',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户信息表';

-- 2. 中国省/市/县数据表
CREATE TABLE IF NOT EXISTS china (
    id INT(11) NOT NULL AUTO_INCREMENT COMMENT '省/市/县id',
    name VARCHAR(40) DEFAULT NULL COMMENT '省/市/县名',
    parent_id INT(11) DEFAULT NULL COMMENT '上级省/市id',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='中国省/市/县数据表';

-- 3. 城市地点管理表
CREATE TABLE IF NOT EXISTS city (
    city_id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '城市编号',
    city_number INT(11) DEFAULT NULL COMMENT '城市编号',
    createtime DATETIME DEFAULT NULL COMMENT '创建时间',
    updatetime DATETIME DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (city_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='城市地点管理表';

-- 4. 医药公司政策表
CREATE TABLE IF NOT EXISTS company_policy (
    id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '公司政策主键id',
    title VARCHAR(255) DEFAULT NULL COMMENT '政策标题',
    message TEXT DEFAULT NULL COMMENT '政策内容',
    company_id BIGINT(20) DEFAULT NULL COMMENT '公司id',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    update_time DATETIME DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='医药公司政策表';

-- 5. 医生表
CREATE TABLE IF NOT EXISTS doctor (
    id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT 'id(医生信息表)',
    account_id BIGINT(20) DEFAULT NULL COMMENT '账号id',
    age INT(11) DEFAULT NULL COMMENT '年龄',
    hospital VARCHAR(255) DEFAULT NULL COMMENT '所属医院',
    level_id BIGINT(20) DEFAULT NULL COMMENT '医师级别id',
    createtime DATETIME(6) DEFAULT NULL COMMENT '创建时间',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='医生表';

-- 6. 医生级别表
CREATE TABLE IF NOT EXISTS doctor_level (
    id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '级别id',
    name VARCHAR(255) DEFAULT NULL COMMENT '级别名',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='医生级别表';

-- 7. 药品信息表
CREATE TABLE IF NOT EXISTS drug (
    drug_id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '药品信息表id',
    drug_name VARCHAR(255) DEFAULT NULL COMMENT '药名',
    drug_info TEXT DEFAULT NULL COMMENT '药品成分信息',
    drug_effect TEXT DEFAULT NULL COMMENT '药品功能',
    drug_img VARCHAR(255) DEFAULT NULL COMMENT '药品图片url',
    publisher VARCHAR(255) DEFAULT NULL COMMENT '发布者',
    createtime DATETIME(6) DEFAULT NULL COMMENT '创建时间',
    updatetime DATETIME(6) DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (drug_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='药品信息表';

-- 8. 药品药店关系表
CREATE TABLE IF NOT EXISTS drug_sale (
    id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键id',
    drug_id BIGINT(20) DEFAULT NULL COMMENT '药的名称',
    sale_id BIGINT(20) DEFAULT NULL COMMENT '售卖该药的药店的id',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='药品药店关系表';

-- 9. 医药公司表
CREATE TABLE IF NOT EXISTS drugcompany (
    company_id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '药品公司信息表id',
    company_name VARCHAR(255) DEFAULT NULL COMMENT '公司名',
    company_phone VARCHAR(255) DEFAULT NULL COMMENT '公司电话',
    createtime DATETIME DEFAULT NULL COMMENT '创建时间',
    updatetime DATETIME DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (company_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='医药公司表';

-- 10. 必备材料表
CREATE TABLE IF NOT EXISTS material (
    id INT(11) NOT NULL AUTO_INCREMENT COMMENT '编号',
    title VARCHAR(255) DEFAULT NULL COMMENT '标题',
    message TEXT DEFAULT NULL COMMENT '必备材料信息',
    create_time DATETIME DEFAULT NULL COMMENT '创建时间',
    update_time DATETIME DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='必备材料表';

-- 11. 医保政策表
CREATE TABLE IF NOT EXISTS medical_policy (
    id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '医保政策信息表id',
    title VARCHAR(255) DEFAULT NULL COMMENT '政策标题',
    message TEXT DEFAULT NULL COMMENT '简介',
    city_id BIGINT(20) DEFAULT NULL COMMENT '所属城市id',
    create_time VARCHAR(255) DEFAULT NULL COMMENT '创建时间',
    update_time VARCHAR(255) DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='医保政策表';

-- 12. 患者信息表
CREATE TABLE IF NOT EXISTS patient (
    id INT(11) NOT NULL AUTO_INCREMENT COMMENT '患者id',
    pname VARCHAR(255) DEFAULT NULL COMMENT '患者姓名',
    age INT(11) DEFAULT NULL COMMENT '患者年龄',
    sex INT(11) DEFAULT NULL COMMENT '性别：1男，2女',
    state INT(11) DEFAULT NULL COMMENT '状态',
    enter_time DATETIME DEFAULT NULL COMMENT '入院时间',
    out_time DATETIME DEFAULT NULL COMMENT '出院时间',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='患者信息表';

-- 13. 权限表
CREATE TABLE IF NOT EXISTS permission (
    id INT(11) NOT NULL AUTO_INCREMENT COMMENT '权限id',
    pid INT(11) DEFAULT NULL COMMENT '父id',
    name VARCHAR(255) DEFAULT NULL COMMENT '菜单名',
    path VARCHAR(255) DEFAULT NULL COMMENT '路径',
    component VARCHAR(255) DEFAULT NULL COMMENT '组件',
    level INT(11) DEFAULT NULL COMMENT '菜单级别',
    title VARCHAR(255) DEFAULT NULL COMMENT '标题',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='权限表';

-- 14. 角色权限关系表
CREATE TABLE IF NOT EXISTS role_permission (
    id INT(11) NOT NULL AUTO_INCREMENT,
    roleName VARCHAR(11) DEFAULT NULL COMMENT '角色id',
    per_id INT(11) DEFAULT NULL COMMENT '权限id',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='角色权限关系表';

-- 15. 药店信息表
CREATE TABLE IF NOT EXISTS sale (
    sale_id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '药店id',
    sale_name VARCHAR(255) DEFAULT NULL COMMENT '药店名称',
    sale_phone VARCHAR(255) DEFAULT NULL COMMENT '联系电话',
    createtime DATETIME DEFAULT NULL COMMENT '创建时间',
    updatetime DATETIME DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (sale_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='药店信息表';

-- 16. 城市信息详情表
CREATE TABLE IF NOT EXISTS sysregion (
    id INT(11) NOT NULL AUTO_INCREMENT COMMENT '区域主键',
    CityCode VARCHAR(20) DEFAULT NULL COMMENT '城市编码',
    MerName VARCHAR(100) DEFAULT NULL COMMENT '组合名称',
    Lat FLOAT DEFAULT NULL COMMENT '纬度',
    Lng FLOAT DEFAULT NULL COMMENT '经度',
    Level INT(11) DEFAULT NULL COMMENT '区域等级',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='城市信息详情表';

-- 17. 诊治类型表
CREATE TABLE IF NOT EXISTS treat_type (
    id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '诊治类型id',
    name VARCHAR(255) DEFAULT NULL COMMENT '诊治类型名',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='诊治类型表';
